### ISSUE TITLE
Light levels are glitched after dungeon reset

### ISSUE THREAD

**Issue by mb243** [LigerXT5/Labyrinth-Generator#4]
After a timed reset, the catacomb will still be at full lighting even though all torches have been removed. Occurred with 1.10.2 as well as 1.11.

**Comment by LigerXT5** [comment]
On both fan made updates, this was fixed, at least they were.

What version of Spigot?

**Comment by mb243** [comment]
[Mon Nov 21 06:24:21 UTC 2016 INFO] This server is running CraftBukkit version git-Spigot-16c940b-ac99d7d (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

**Comment by LigerXT5** [comment]
I know the original creator had an issue with this break every time an update came around. So far every time a major MC update comes out, this breaks.

**Comment by mb243** [comment]
Sorry to hear that :( I'm not familiar enough with the code to offer to help, but hopefully someone else is and can help with this.

**Comment by mb243** [comment]
This is an old issue, does not have recent activity, and I'm not even sure the original issue is valid anymore. Closing this issue to save work for the maintainers.
