### ISSUE TITLE
Vault string for currency is ignored, 'coins' is used instead

### ISSUE THREAD

**Issue by mb243** [LigerXT5/Labyrinth-Generator#5]
When giving gold to players to mob kills, the word 'coins' is used instead of the vault string for the currency name. This should be changed the use the vault string to mesh with the in-game economy.

**Comment by LigerXT5** [comment]
I don't recall the currency function actually working, the last few updates the original creator done, he mentioned he disabled the feature to be revamped.

I'll see what I can do about correcting this.

**Comment by mb243** [comment]
I can confirm the currency feature works, it's just a matter of pulling the correct string from Vault and using it instead of the word 'coins':

https://github.com/Blockhead2/Catacombs/blob/b02cacae13a6fbec2f99a3c94b23b6254c5e0c7d/src/main/java/net/steeleyes/catacombs/CatMob.java#L207

https://github.com/Blockhead2/Catacombs/blob/b02cacae13a6fbec2f99a3c94b23b6254c5e0c7d/src/main/java/net/steeleyes/catacombs/Dungeon.java#L1355

**Comment by mb243** [comment]
This is an old issue, does not have recent activity, and I'm not even sure the original issue is valid anymore. Closing this issue to save work for the maintainers.
