### ISSUE TITLE
Missing commits?

### ISSUE THREAD

**Issue by jemcdevitt** [LigerXT5/Labyrinth-Generator#6]
I'm trying to build this to work with 1.12.2 and I realize this code hasn't had a commit in a few years, but there is a whole series of functions supposedly in CatUtils that are being used by Monsters.java that are not present.  Methods like **improveDurability**, **useOne**, etc.  Some of them I can probably intuit and possibly create but I wanted to see if there was a missing version of CatUtils that perhaps didn't get committed? 

Looks like the original version from Blockhead2/Catacombs has the missing functions.  I'm going to try and work with the original code.

**Comment by LigerXT5** [comment]
I haven't made any significant changes. It is possible the two prior authors who updated the plugin, before I made this github setup, may have removed them.

I haven't played much Minecraft in a while. Though I still run a small MC server for coworkers and few friends, the server is 95% vanilla. With life and work, I haven't had much time, or motivation, to run a public server and run many plugins, including this.

I wish you the best.

**Comment by jemcdevitt** [comment]
Appreciate the feedback.  After some code changes I was able to get a successful build from the original version, but couldn't see if it was working.  Plugin appears to load in a 1.12.2 server but flying around a newly created world never located a hut.    May play around a bit more with it.
